#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOuRCE[0]}") && pwd)

# just in case
mkdir -p $HOME/.config
mkdir -p $HOME/.local/bin

rm -rf $HOME/.bashrc
ln -s $DOTFILES/bashrc $HOME/.bashrc

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim
