# prompt
# PROMPT='%F{green}%n@X%~: %f'

# set editor for zsh
export EDITOR=nvim
export VISUAL=nvim

# Editor
autoload -z edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-comand-line
# vi keybind
bindkey -v


source $HOME/dotfiles/zsh/aliases
source $HOME/dotfiles/zsh/add-git-status
source $HOME/dotfiles/zsh/promptline

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
