# prompt
# PROMPT='%F{green}%n@X%~: %f'

# Editor keybindings
autoload -z edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line
# vi keybind
# bindkey -v


source $HOME/dotfiles/zsh/aliases
source $HOME/dotfiles/zsh/add-git-status
source $HOME/dotfiles/zsh/promptline

# setup fzf key bindings and fuzzy completion.
source $HOME/dotfiles/zsh/fzf-key-bindings.zsh

# setup completion for watson (with caching for faster startup)
autoload -Uz compinit
# Only regenerate compdump once per day
if [[ -n ${ZDOTDIR:-$HOME}/.zcompdump(#qN.mh+24) ]]; then
    compinit
else
    compinit -C
fi
